### ISSUE TITLE
unable to clone git repo from github saas to gitbash

### ISSUE THREAD

**Issue by sudeeshn** [gitblit-org/gitblit#1374]
Error:
fatal: unable to access 'https://github.com/XXXX/': Empty reply from server

**Comment by TomaszSzt** [comment]
It is hard to guess what @sudeeshn had on mind but maybe this will help.

Try:

git clone https://github.com/gitblit/gitblit

instead of, what naturally comes to mid

git clone https://github.com/gitblit

yea, it took me a bit to figure it out.

**Comment by flaix** [comment]
I still have no idea what the request was about. As there was no further communication, I am closing this as Invalid.
